export let CommentsImg = document.querySelectorAll('.component__comment-box__tittle__img')
export let CommentsName = document.querySelectorAll('.component__comment-box__tittle__author')
export let CommentsTime = document.querySelectorAll('.component__comment-box__tittle__time')
export let CommentsConetent = document.querySelectorAll('.component__comment-box__content')
export let CommentsScore = document.querySelectorAll('.component__comment-box__elements__rating__number')

export let firstPlus = document.querySelector('#first-plus')
export let secondPlus = document.querySelector('#second-plus')
export let firstMinus = document.querySelector('#first-minus')
export let secondMinus = document.querySelector('#second-minus')
export let replyPlus = document.querySelector('#reply-plus')
export let replyMinus = document.querySelector('#reply-minus')
export let firstScore = document.querySelector('#first-score')
export let secondScore = document.querySelector('#second-score')
export let replyScoreNumber = document.querySelector('#reply-score')
export let firstReplyBtn = document.querySelector('#first-reply-btn')
export let secondReplyBtn = document.querySelector('#second-reply-btn')
export let thirdReplyBtn = document.querySelector('#third-reply-btn')
export let firstComment = document.querySelector('#first-comment')
export let secondComment = document.querySelector('#second-comment')
export let firstReply = document.querySelector('#first-reply')
export let firstReplyContent = firstReply.querySelector('.component__comment-box__content')
export let secondReply = document.querySelector('#second-reply')
export let secondReplyDeleteBtn = secondReply.querySelector('.component__comment-box__elements__reply__text--delete')
export let secondReplyEditBtn = secondReply.querySelector('.component__comment-box__elements__reply__text--edit')
export let secondReplyContent = secondReply.querySelector('.component__comment-box__content')

export let ReplyImg = document.querySelectorAll('.component__comment-box--reply .component__comment-box__tittle__img')
export let ReplyName = document.querySelectorAll('.component__comment-box--reply .component__comment-box__tittle__author')
export let ReplyTime = document.querySelectorAll('.component__comment-box--reply .component__comment-box__tittle__time')
export let ReplyConetent = document.querySelectorAll('.component__comment-box--reply .component__comment-box__content')
export let ReplyScore = document.querySelectorAll('.component__comment-box--reply .component__comment-box__elements__rating__number')

export let addCommentImg = document.querySelector('.component__comment-box--add__elements__img')
export let addBtn = document.querySelector('.component__comment-box--add__elements__btn')
export let commentsList = document.querySelector('.component')
export let addCommentBox = document.querySelector('.component__comment-box--add')